---
- name: Copy binary
  copy:
    src: "{{GAIACLI_BINARY}}"
    dest: /usr/bin/enigmagozcli
    mode: 0755
  notify: restart enigmagozcli

- name: Copy service
  template:
    src: enigmagozcli.service.j2
    dest: /etc/systemd/system/enigmagozcli.service
  notify: systemctl
