---
- name: Stop service
  service: name=enigmagozd state=stopped

- name: Delete files
  file: "path={{item}} state=absent"
  with_items:
    - /usr/bin/enigmagozd
    - /home/enigmagozd/.enigmagozd
    - /home/enigmagozd/.enigmagozcli
