---
- name: Fetch genesis.json
  fetch: "src=/home/enigmagozd/.enigmagozd/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: enigmagozd

- name: Fetch config.toml
  fetch: "src=/home/enigmagozd/.enigmagozd/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: enigmagozd
