---
- name: Copy binary
  copy:
    src: "{{BINARY}}"
    dest: /usr/bin/enigmagozd
    mode: 0755
  notify: restart enigmagozd

- name: Copy new genesis.json file, if available
  when: "GENESISFILE is defined and GENESISFILE != ''"
  copy:
    src: "{{GENESISFILE}}"
    dest: /home/enigmagozd/.enigmagozd/config/genesis.json
  notify: restart enigmagozd

- name: Download genesis.json URL, if available
  when: "GENESISURL is defined and GENESISURL != ''"
  get_url:
    url: "{{GENESISURL}}"
    dest: /home/enigmagozd/.enigmagozd/config/genesis.json
    force: yes
  notify: restart enigmagozd

- name: Reset network
  when: UNSAFE_RESET_ALL | default(false) | bool
  command: "sudo -u enigmagozd enigmagozd unsafe-reset-all"
  notify: restart enigmagozd
